ifdef::env-github[]
https://htmlpreview.github.io/?https://github.com/osodevops/dynamic-ecommerce-discounts-with-redpanda/blob/main/discounts-processor/README.html[Open README.html]
endif::env-github[]
ifndef::env-github[]
= Testing the Discounts Processor Implementation
Paulo Jerônimo
include::common/head.adoc[]

== Testing

Assuming that you are in this directory (`discounts-processor`), to test this backend you will need to open some terminals.

In my case, since I love to use {Tmux} I'll open it with this command:

[,console]
----
$ tmux new-session -d \; send-keys "less README.adoc" C-m \; split-window -v \; split-window -v \; select-pane -t 0 \; attach
----

This will open a window with three panes:

. The first one will keep showping this document.
. The second pane (in the middle) I'll use to show the logs for the disconts-processor container.
. The last pane (below in the screen) I'll use to execute the tests.

[TIP]
====
. You don't need to use {Tmux} if you are unfamiliar with it.
Just open three terminals (one to see this doc plus other two).
. If you are using Tmux, the combination prefix key (kbd:[Ctrl+b]) plus `M` can be useful to enable or disable the mouse support.
====

So, in the terminal on the middle, type:

[,console]
----
$ ./test.sh reconfigure discount-event-sender false
$ ./test.sh start-services
----

In the lower terminal opened, type:

[,console]
----
$ ./test.sh run SingleProduct
$ ./test.sh restart-services

$ ./test.sh run MultiProduct
$ ./test.sh restart-services

$ ./test.sh run MostViewedMultipleViewsPerProduct
$ ./test.sh restart-services

$ # For the following test, check if the event is producted in Redpanda Console manually.
$ ./test.sh run MostViewedMultipleViewsPerProduct now
$ ./test.sh stop-services
----

After all these tests, remember to reconfigure discount-event-sender again:

[,console]
----
$ ./test.sh reconfigure discount-event-sender true
----

That's it!
